const actionTypes = {
  ADD_TODO: 'ADD_TODO',
  EDIT_TODO: 'EDIT_TODO',
  SELECT_TODO: 'SELECT_TODO',
  UNSELECT_TODO: 'UNSELECT_TODO',
  TODOS_IS_LOADED: 'TODOS_IS_LOADED',
  TODOS_IS_LOADING: 'TODOS_IS_LOADING',
  TODOS_HAS_FAILED: 'TODOS_HAS_FAILED',
  TODOS_FETCH_DATA_SUCCESS: 'TODOS_FETCH_DATA_SUCCESS',
};

export default actionTypes;
